#!/usr/bin/env python3
import json, pathlib

COURSE_PATH = pathlib.Path(__file__).parent.parent / "content/courses/mie-201/course.json"

LEARN = {
  "what-is-a-business": {
    "openingQuestion": "Amazon started as an online bookstore run from Jeff Bezos's garage. Today it owns grocery stores, a film studio, and a cloud-computing empire that powers Netflix. At what point does a 'business' stop being one thing and become something else entirely?",
    "anchor": "A business is any organization that combines resources to create value for customers in exchange for revenue.",
    "anchorSummary": "A business combines resources to create value, then exchanges that value for money.",
    "mechanism": "The word 'business' hides enormous variety — a sole proprietor selling tamales from a cart and Apple Inc. are both businesses. What they share is a core logic: acquire inputs (labor, capital, materials, ideas), transform those inputs into something more valuable, and exchange that output for money from customers who want it.\n\nThree ideas make this definition sharp. First, profit is not the definition of a business — it is an outcome. A business can operate at a loss for years (Amazon did for most of the 1990s) and still be a business. What matters is the intent to exchange value for revenue. Second, value creation is relative to the customer: something is only 'more valuable' if a customer agrees it is, which means the customer, not the producer, is the ultimate judge. Third, businesses exist within a broader ecosystem — they rely on suppliers, governments, financial systems, and labor markets. No business is self-sufficient.\n\nUnderstanding what a business is matters because every functional area — accounting, marketing, finance, operations, HR — is a specialized tool for solving one part of the value-creation problem. Accounting measures the value created. Marketing finds customers who will pay for it. Operations delivers it reliably. Finance funds the inputs. When you know the core logic, each function's role becomes obvious. How this connects to other business functions: every function serves the core value-creation loop — if the loop breaks (no customers, no revenue, no inputs), all functions lose their purpose.",
    "mechanismSummary": "Businesses combine inputs into customer value and exchange it for revenue — every function serves that loop.",
    "boundaryConditions": "This definition blurs at the edges. Nonprofits create value but don't pursue profit. Government agencies provide services but fund them through taxes, not voluntary exchange. Platform businesses like Uber or Airbnb create value partly by connecting other parties, raising the question of whether the platform or the drivers/hosts are 'the business.' In complex modern economies, pure 'businesses' often blend with regulatory, nonprofit, and platform elements.",
    "example": "When Netflix launched in 1997, it rented DVDs by mail — a clear business: pay $4, get a DVD, return it. By 2007 it had added streaming. By 2013 it was producing original content. Each pivot changed what inputs were needed (warehouses → servers → writers and directors), what value was delivered (convenience → instant access → exclusive content), and who the competitors were (Blockbuster → cable TV → every studio). The business logic — combine resources, create value, exchange for revenue — stayed constant even as every detail changed.",
    "bridgeToAbstract": "Whether the business is a food truck or a Fortune 500 company, the core logic is always the same: find a way to create value that customers will pay for, and build a system that delivers it sustainably. Everything else in business education is a tool for doing that better.",
    "keyPoints": [
      "Students confuse profit with purpose — profit is an outcome of successful value creation, not the definition of a business itself",
      "The customer decides what counts as 'value' — a product with great features that nobody wants is not creating value in the economic sense",
      "Every business function (marketing, ops, finance, HR) exists to serve the value-creation loop — understanding the loop first makes each function's role clear"
    ]
  },
  "stakeholders": {
    "openingQuestion": "In 2018, CVS Health banned tobacco sales — costing itself $2 billion in annual revenue — to align with its new health-company identity. Shareholders lost money. Customers who smoked lost convenience. But other customers, insurers, and employees applauded. Who was CVS actually obligated to?",
    "anchor": "A stakeholder is anyone who affects or is affected by a business's decisions, not just the people who own shares in it.",
    "anchorSummary": "Stakeholders are all parties affected by a firm — owners, employees, customers, communities, and more.",
    "mechanism": "Shareholder theory says businesses exist solely to maximize returns for owners. Stakeholder theory says that view is too narrow: a business's decisions ripple outward to employees (who need jobs and safe conditions), customers (who need reliable products), suppliers (who depend on payment), communities (who bear environmental and social costs), and governments (which provide infrastructure and rule of law). All of these groups have something at stake.\n\nStakeholders are typically divided into two groups. Primary stakeholders have a direct economic relationship with the firm: shareholders, employees, customers, suppliers, and creditors. Secondary stakeholders are affected but don't have a direct economic link: communities, media, activist groups, governments as regulators. Both groups can create serious problems for a business that ignores them — employees can quit, customers can boycott, governments can regulate, communities can generate reputational damage that drives customers away.\n\nManaging stakeholders is not charity — it is risk management and relationship capital. A firm that treats suppliers as adversaries will find them abandoning it in a crisis. One that ignores employee morale will face turnover costs and lower productivity. One that poisons a local river will face regulatory fines, lawsuits, and talent recruitment problems. How this connects to other business functions: every function manages a specific set of stakeholders — marketing manages customers, HR manages employees, finance manages investors and creditors, operations manages suppliers. Strategy integrates all of them.",
    "mechanismSummary": "Stakeholders include everyone affected by a firm's decisions; managing them is risk management, not just ethics.",
    "boundaryConditions": "Stakeholder theory doesn't provide a clear tiebreaker when stakeholders conflict — as CVS discovered when protecting its health identity cost shareholders billions. In practice, shareholders retain a privileged position because they bear residual risk and have legal rights to firm assets. The model also struggles in situations where the 'community' is diffuse or poorly organized, making their interests hard to represent. Some critics argue that trying to serve all stakeholders simultaneously leads to serving none of them well.",
    "example": "When Nike faced revelations in the 1990s about labor conditions in overseas factories, it discovered that secondary stakeholders — advocacy groups, journalists, and college students who boycotted Nike gear on campuses — could do more economic damage than any primary stakeholder dispute. Nike's factories were in compliance with local laws and its suppliers were separate entities. But public opinion didn't make those distinctions. Nike eventually created the Fair Labor Association and transformed its supply chain monitoring. A secondary stakeholder crisis forced a complete overhaul of operations and supplier relationships.",
    "bridgeToAbstract": "Every business decision has a stakeholder map. Understanding who is affected, how much power they have, and what they need is not a soft-skills exercise — it is a core part of strategic risk management that touches every function from operations to finance.",
    "keyPoints": [
      "Students often equate stakeholders with shareholders — shareholders are one type of stakeholder, not the full set",
      "Secondary stakeholders (activists, media, communities) can impose larger costs than primary stakeholders if they mobilize public opinion or trigger regulation",
      "Every business function manages different stakeholders: marketing = customers, HR = employees, finance = investors — strategy must integrate them all"
    ]
  },
  "factors-of-production": {
    "openingQuestion": "OpenAI trained GPT-4 using thousands of specialized chips, billions of dollars in cloud computing, massive datasets scraped from the internet, and hundreds of top AI researchers. Which of those inputs is actually the scarce one — and who controls it?",
    "anchor": "Factors of production are the four categories of inputs every economy uses to produce goods and services: land, labor, capital, and entrepreneurship.",
    "anchorSummary": "Land, labor, capital, and entrepreneurship are the four inputs all production requires.",
    "mechanism": "Economists have long observed that all productive activity draws on a common set of resource types. Land covers all natural resources — physical land, minerals, water, oil, timber, and in the modern economy, electromagnetic spectrum and data. Labor is human effort: physical work, cognitive work, creative work. Capital is human-made resources used to produce other goods — factories, machines, tools, software, infrastructure. Entrepreneurship is the human capacity to combine the other three productively: to take risk, make decisions under uncertainty, and organize land, labor, and capital into something that creates value.\n\nEach factor has a corresponding return. Land earns rent. Labor earns wages. Capital earns interest or profit on investment. Entrepreneurship earns profit (or absorbs losses). Understanding factor markets helps explain why businesses locate where they do, hire the workers they do, and make the capital investments they do — each decision is about acquiring the right factor at the right cost.\n\nIn the digital economy, a fifth factor is sometimes added: data or information. Data increasingly functions like a factor of production — it is an input that can be combined with labor and capital to produce valuable outputs, and controlling large amounts of it creates competitive advantage. How this connects to other business functions: operations decides which factors to use in what combination; finance raises capital to pay for them; HR acquires and manages labor; strategy decides which factors to make core competencies versus outsource.",
    "mechanismSummary": "Land, labor, capital, and entrepreneurship are the four inputs; understanding their costs shapes every major business decision.",
    "boundaryConditions": "The four-factor model was developed for industrial economies and fits manufacturing well. It fits knowledge-intensive businesses less cleanly — what 'factor' is a software algorithm, a brand reputation, or a network effect? These assets don't fit neatly into land, labor, or capital. Additionally, factors of production are not always bought in markets; they can be built internally (training labor, developing proprietary technology), which blurs the line between a factor and a competency.",
    "example": "When Tesla chose to build its Gigafactory in Nevada instead of California, it was making a classic factor-of-production decision. Nevada offered cheaper land, lower labor costs, proximity to lithium deposits (natural resource), and significant tax incentives to attract capital. California offered more skilled labor but at much higher wages. Tesla's decision balanced all four factors — and by securing lithium supply early, it gained an advantage in the key natural resource its product required. The factory itself became a capital asset that lowered per-unit production costs.",
    "bridgeToAbstract": "Every business is in the business of acquiring factors of production at a cost and combining them in ways that produce more value than the inputs cost. Competitive advantage often comes from accessing a factor others cannot — a unique location, hard-to-hire talent, proprietary technology, or entrepreneurial insight the competition lacks.",
    "keyPoints": [
      "Students often think 'capital' means money — in economics, capital means physical or productive assets; money is a claim on capital, not capital itself",
      "Entrepreneurship is the factor that organizes all the others — without it, land, labor, and capital sit idle or get combined inefficiently",
      "Operations, HR, and finance each manage one or more factors of production — strategy determines which factors to own versus buy from markets"
    ]
  },
  "economic-systems": {
    "openingQuestion": "Cuba has universal healthcare and near-zero homelessness, but Cubans wait years for a car and earn an average of $30 per month. The U.S. has some of the most innovative companies in history but also tent cities blocks from Silicon Valley offices. What does that tradeoff actually reveal about how economies are organized?",
    "anchor": "An economic system is the set of rules and institutions a society uses to decide who produces what, how, and for whom.",
    "anchorSummary": "Economic systems are the rules societies use to allocate resources and answer who produces what for whom.",
    "mechanism": "Every society faces the same three fundamental economic questions: What goods and services will be produced? How will they be produced? For whom will they be produced — who gets what? Different systems answer these questions differently.\n\nIn a command economy, a central authority (usually the government) makes these decisions. Production targets are set by planners, prices are controlled, and the distribution of output is directed by policy. The Soviet Union was the canonical example. In a pure market economy, these decisions are made by millions of individual buyers and sellers interacting through prices. Rising prices signal scarcity and attract producers; falling prices signal surplus and drive production down. Most modern developed economies are mixed economies — they use markets as the primary allocation mechanism but use government intervention to correct market failures (externalities, public goods, monopoly power), provide safety nets, and address equity concerns.\n\nFor businesses, economic systems determine the rules of the game. In a market system, businesses compete for customers and respond to price signals. In a mixed system, they also navigate regulation, taxation, and subsidies. The degree of government intervention shapes which industries are viable, what costs businesses must bear (minimum wages, environmental standards), and how aggressively companies can price and compete. How this connects to other business functions: accounting rules, labor law, environmental regulations, antitrust law — all of these are functions of the economic system in which a business operates.",
    "mechanismSummary": "Economic systems determine who decides resource allocation — government, markets, or both — shaping the rules all businesses operate under.",
    "boundaryConditions": "No pure market or pure command economy exists in practice. Even the most market-oriented economies (U.S., U.K.) have significant government roles in healthcare, education, defense, and financial regulation. Even the most centrally planned economies (Cuba, North Korea) have informal or black markets. The continuum between pure command and pure market is a spectrum, not a binary. Additionally, the 'best' system depends on what you are optimizing for — innovation speed, equity, stability, or sustainability — and these objectives frequently conflict.",
    "example": "China's economy is the most studied hybrid in the world. The Chinese Communist Party sets five-year industrial plans, controls state-owned enterprises in key sectors (energy, banking, telecom), and actively picks industrial winners (EVs, semiconductors, solar). But within those guardrails, market competition among private firms is intense — Alibaba, Tencent, and BYD all compete ferociously for customers. Apple manufactures in China because the system delivers cost-competitive labor, subsidized infrastructure, and politically enforced stability — all products of the command side — while also enabling the market-driven supplier competition Apple needs.",
    "bridgeToAbstract": "Businesses don't operate in a vacuum — they operate inside economic systems that determine who they can hire, what they must pay, what they can charge, and what they owe in taxes. Understanding economic systems is understanding the operating environment every business function must work within.",
    "keyPoints": [
      "Students often treat 'free market' as synonymous with 'no rules' — in practice, markets require property rights, contract enforcement, and regulatory stability, all of which require government",
      "The same business model can be highly profitable in one economic system and illegal or impossible in another — economic system analysis is part of market entry strategy",
      "Accounting standards, labor law, environmental regulation, and antitrust rules are all products of a society's economic system — they affect every business function"
    ]
  },
  "supply-demand-and-business": {
    "openingQuestion": "In 2021, the global semiconductor shortage caused Ford to idle factories full of nearly complete F-150 trucks — the best-selling vehicle in America — because each truck was missing one $3 chip. How does a $3 part shut down a $50,000 product?",
    "anchor": "Supply and demand are the forces that determine market prices and quantities, signaling to businesses where value can be created and what it is worth.",
    "anchorSummary": "Supply and demand set prices and quantities, telling businesses what to make and what they can charge.",
    "mechanism": "Demand describes how much customers want a product at different prices — the higher the price, the less they want (generally). Supply describes how much producers will offer at different prices — the higher the price, the more profitable it is to produce, so more will be offered. The intersection of supply and demand sets the equilibrium price — the price at which quantity supplied equals quantity demanded.\n\nFor businesses, price signals do three things. First, they communicate information: a rising price for a product tells producers that demand exceeds supply and more production is profitable. A falling price signals the reverse. Second, they allocate resources: businesses shift production toward higher-priced, higher-margin goods and away from lower-margin ones. Third, they reveal customer value: what customers will pay is the most direct measure of how much value they perceive.\n\nShifts in supply or demand move equilibrium prices and quantities. When demand increases (more buyers, higher incomes, better substitutes disappear), prices rise. When supply decreases (fewer producers, higher input costs, disruptions), prices rise. The semiconductor shortage was a double shock: pandemic demand for electronics surged (demand shift right) while factory shutdowns in Asia cut supply (supply shift left). For Ford, the chip was the binding constraint — one undersupplied component prevented the entire product from being finished. How this connects to other business functions: marketing shapes demand through advertising and positioning; operations determines supply capacity; finance funds the investment needed to shift supply curves.",
    "mechanismSummary": "Prices emerge where supply meets demand; they signal value, allocate resources, and reveal where businesses should focus.",
    "boundaryConditions": "Supply and demand models assume many buyers and sellers, no single party controls price, and products are relatively homogeneous. These conditions often don't hold. In markets with few sellers (oligopoly) or one (monopoly), prices can be set well above equilibrium for extended periods. In markets with strong brand differentiation, customers may pay prices that don't reflect simple supply/demand logic. In markets with significant switching costs (enterprise software), demand curves are less elastic than the model predicts.",
    "example": "When Beyoncé announced the Renaissance World Tour in 2023, Ticketmaster's dynamic pricing algorithm let prices adjust to revealed demand — some floor tickets listed at $300 jumped to over $2,000 within hours. This was supply (seats) and demand (millions of fans) intersecting in real time. The backlash — calls for antitrust action, congressional hearings — showed that economically rational pricing can be politically and reputationally harmful. Operations (venue capacity) set supply; marketing (the artist's brand) shaped demand; finance (revenue maximization) drove the pricing algorithm; but the customer relations fallout was a consequence none of the functions managed in advance.",
    "bridgeToAbstract": "Supply and demand are not just economics textbook abstractions — they are the forces every pricing, production, and investment decision responds to. A business that understands what moves its demand curve and what constraints its supply curve can anticipate market changes faster than one that treats price as a fixed input.",
    "keyPoints": [
      "Students often think businesses 'set' prices freely — in competitive markets, price is largely determined by supply and demand; a business that prices too high loses customers to rivals",
      "Demand shifts and supply shifts are different — confusing them leads to wrong predictions about price and quantity effects",
      "Every business function touches supply or demand: marketing shifts demand curves, operations determines supply capacity, finance funds supply expansion — strategy coordinates all three"
    ]
  },
  "business-cycles": {
    "openingQuestion": "Between 2008 and 2009, U.S. GDP fell just 4.3% — not even close to the Great Depression — but unemployment hit 10%, foreclosures topped 5 million, and Lehman Brothers, one of the oldest investment banks in America, ceased to exist. Why does a 4% drop in output cause so much destruction?",
    "anchor": "Business cycles are recurring patterns of expansion and contraction in economic activity that affect all firms, regardless of industry or management quality.",
    "anchorSummary": "Economies expand and contract in recurring cycles; every business operates within these cycles and must plan for them.",
    "mechanism": "A business cycle has four phases: expansion (rising GDP, employment, investment), peak (the top of the cycle), contraction or recession (falling GDP, rising unemployment, reduced investment), and trough (the bottom, before the next expansion begins). A recession is technically two consecutive quarters of declining GDP, but its practical effects — layoffs, reduced consumer spending, tighter credit — begin before and extend well after that technical definition.\n\nBusinesses are affected differently depending on their sensitivity to the cycle. Cyclical businesses — cars, luxury goods, construction, advertising — see demand fall sharply in recessions because customers defer purchases. Defensive businesses — grocery stores, utilities, basic pharmaceuticals — maintain relatively stable demand because customers must buy their products regardless. This distinction matters enormously for financial planning: a cyclical business that doesn't build cash reserves during expansion can face existential risk in contraction.\n\nMacroeconomic variables that businesses track include GDP growth, unemployment rates, interest rates (set by the Federal Reserve), and inflation. Rising interest rates increase borrowing costs — slowing capital investment and consumer spending. Inflation erodes purchasing power and squeezes margins if input costs rise faster than output prices. How this connects to other business functions: finance must adjust capital structure and cash management through the cycle; operations must manage workforce and capacity; marketing must adapt messaging and pricing; strategy must reconsider expansion or contraction plans based on macroeconomic signals.",
    "mechanismSummary": "Business cycles are inevitable; cyclical vs. defensive sensitivity and cash management determine which firms survive contractions.",
    "boundaryConditions": "Business cycles are real but not perfectly predictable — their timing, depth, and sector impacts are uncertain. Forecasters regularly fail to call recessions accurately. Additionally, globalization means that a recession in one major economy spreads through trade and financial linkages to others, making purely domestic cycle management insufficient. Some industries (defense, government contracting) are counter-cyclical — they may expand when the economy contracts, because government spending tends to increase during downturns.",
    "example": "Ford and GM both nearly went bankrupt in 2008–2009 because they had built their business models around the expansion phase — high capacity, heavy debt, large payrolls. When auto sales dropped 40% in a matter of months, neither company had the cash reserves or the flexible cost structure to survive. GM took a $50 billion government bailout and went through bankruptcy. Meanwhile, Toyota — which had maintained leaner operations and stronger cash reserves — survived without government assistance and used the downturn to capture market share. Same recession, radically different outcomes based on how each company had managed financial and operational risk across the cycle.",
    "bridgeToAbstract": "Business cycles are one of the most powerful external forces shaping what is possible for any business at any moment. Understanding where the economy is in the cycle — and how your specific business is exposed to it — should inform every major decision in finance, operations, and strategy.",
    "keyPoints": [
      "Students often assume recessions are primarily caused by bad management — most recessions are systemic; even well-managed companies can fail if they haven't prepared financially for the downside",
      "Cyclical vs. defensive distinction matters for career choice too — cyclical industries hire aggressively in expansions and cut sharply in contractions",
      "Interest rate changes by the Fed affect borrowing costs across every business function: capital investment (finance), inventory financing (operations), consumer credit (marketing and demand)"
    ]
  },
  "sole-proprietorships": {
    "openingQuestion": "The average food truck owner works 60-hour weeks, owns their own truck, handles their own Instagram marketing, manages their own inventory, files their own taxes — and if someone slips and falls at the window, can potentially lose their personal savings account. Is that freedom or a trap?",
    "anchor": "A sole proprietorship is a business owned and operated by one person with no legal separation between owner and business.",
    "anchorSummary": "A sole proprietorship merges owner and business legally — maximum simplicity, maximum personal risk.",
    "mechanism": "A sole proprietorship is the simplest and most common business form in the United States. Formation requires no paperwork beyond any local business licenses; you simply begin operating. The owner receives all profit and bears all losses. There is no legal distinction between the owner's assets and the business's assets — they are the same.\n\nThe central feature — and the central risk — of a sole proprietorship is unlimited personal liability. If the business incurs a debt or a lawsuit judgment it cannot pay, creditors can seize the owner's personal assets: savings accounts, car, home. For many small service businesses (plumbing, tutoring, freelance design) where the main risk is contract disputes or minor accidents, this risk is manageable. For businesses with significant physical hazards, large inventories, or toxic materials, it can be catastrophic.\n\nSole proprietorships pass their income directly through to the owner's personal tax return — the business does not pay taxes separately. This simplicity has a cost: the owner also pays self-employment tax on top of income tax, which covers both the employer and employee portions of Social Security and Medicare. How this connects to other business functions: a sole proprietor is simultaneously the CEO, CFO, CMO, and COO — every function collapses into one person, which is both an efficiency advantage (no coordination overhead) and a growth ceiling (one person's time and capital is the limit).",
    "mechanismSummary": "Sole proprietorships are simple and owner-controlled but carry unlimited personal liability and scale only with the owner.",
    "boundaryConditions": "Sole proprietorships work well for low-liability, low-capital service businesses where the owner is also the primary value creator. They become problematic when: the business takes on debt that exceeds the owner's personal net worth; the risk of injury, property damage, or lawsuits is high; the business needs to raise outside capital (sole props cannot issue shares); or the business grows to require multiple workers and management systems. At those points, shifting to an LLC or corporation becomes rational.",
    "example": "Ina Garten (the Barefoot Contessa) started as a sole proprietor running a specialty food store in East Hampton in 1978. She was the buyer, the marketer, the manager, and the cook. When the business expanded — first a cookbook, then a Food Network show, then a product line — she had to restructure, adding legal entities, staff, and formal accounting. The sole proprietorship gave her the flexibility to start without bureaucracy, but scaling required adopting a more complex business form. Most successful small businesses start as sole props and evolve as their liability, capital, and management needs grow.",
    "bridgeToAbstract": "A sole proprietorship is the default business form — it's what you have when you start working for yourself without doing anything else. Its simplicity is real, but so is its constraint: personal liability ties the business's risk directly to the owner's personal financial life, which shapes every decision about growth, debt, and insurance.",
    "keyPoints": [
      "Students often think 'sole proprietorship' means small — sole props range from a teenager mowing lawns to a self-employed attorney with millions in annual revenue",
      "Unlimited liability is the critical constraint: one large lawsuit can eliminate personal savings accumulated over decades",
      "A sole proprietor handles every business function alone — understanding all functions (accounting, marketing, operations, finance) is not optional for survival"
    ]
  },
  "partnerships": {
    "openingQuestion": "Ben and Jerry's started as two friends with a $5 correspondence course in ice cream making and a $12,000 investment — half of it borrowed. They shook hands, pooled their money, and opened a converted gas station in Vermont. What happens to that business if Ben wants to sell and Jerry doesn't?",
    "anchor": "A partnership is a business owned by two or more people who share profits, losses, and — in a general partnership — unlimited personal liability.",
    "anchorSummary": "Partnerships pool resources and skills across multiple owners, but general partners share unlimited personal liability.",
    "mechanism": "Partnerships exist on a spectrum based on how liability is distributed. In a general partnership, all partners have unlimited personal liability — each partner can be held personally responsible for the debts and legal judgments incurred by any other partner acting on behalf of the business. This joint and several liability can be devastating: if your partner makes a catastrophic decision, your personal assets are exposed. In a limited partnership, there is at least one general partner (unlimited liability, active management) and one or more limited partners who contribute capital but have liability limited to their investment and no role in day-to-day management. A limited liability partnership (LLP) is common in professional services — law firms, accounting firms — where all partners have limited liability but all participate in management.\n\nPartnerships are governed by a partnership agreement — a contract between partners specifying how profits and losses are divided, who makes which decisions, what happens when a partner wants to leave or dies, and how disputes are resolved. Without a written agreement, state law imposes default rules, which often produce outcomes neither partner would have chosen.\n\nPartnerships pass income through to partners' personal tax returns (pass-through taxation), avoiding the double taxation that C-corporations face. How this connects to other business functions: a partnership's greatest strategic advantage is combining complementary skills — one partner's operational expertise with another's marketing or financial skill — but this requires explicit agreements about decision authority in each function.",
    "mechanismSummary": "Partnerships combine capital and skills across owners, with liability structure varying from unlimited (general) to limited by investment.",
    "boundaryConditions": "Partnerships often struggle with growth beyond the founding partners because adding new partners is legally complex and culturally disruptive. The moment profits are large enough to attract passive investors who want returns without management roles, the limited partnership or LLC becomes more attractive. Additionally, partnership dissolution — when one partner dies, retires, or wants to exit — can be enormously disruptive if not pre-planned in the partnership agreement.",
    "example": "The accounting firm Ernst & Young (now EY) was originally a partnership of Ernest Ernst and Arthur Young, who merged their separate accounting firms in 1989. For most of its history, EY operated as a partnership — partners owned the firm, shared profits, and bore professional liability collectively. This structure aligned partners' incentives (they ate what they killed) and allowed profits to flow directly to individuals without corporate tax. As of 2022, EY explored breaking up into an audit firm (remaining a partnership) and a consulting firm (going public) — precisely because the partnership structure, optimal for stable professional services, was limiting the consulting arm's ability to raise capital for growth.",
    "bridgeToAbstract": "Partnerships are a natural evolution from the sole proprietorship when a business needs more capital, more skills, or more capacity than one person can provide. The trade-off is clear: more resources, more complexity, and in general partnerships, shared exposure to each partner's decisions.",
    "keyPoints": [
      "Joint and several liability in a general partnership means you can be liable for your partner's mistakes, not just your own — a fact many new entrepreneurs overlook",
      "A written partnership agreement is not optional: without one, state default rules govern what happens when partners disagree, exit, or die",
      "Partnerships excel when partners bring complementary skills across functions — a finance-oriented partner paired with a marketing- or operations-oriented partner"
    ]
  },
  "corporations": {
    "openingQuestion": "When Enron collapsed in 2001, its executives went to prison. Its shareholders lost $74 billion. But no individual shareholder had to pay Enron's debts personally. That's not an accident — it's a legal design choice made in the 19th century. Who decided that shareholders shouldn't be on the hook, and why?",
    "anchor": "A corporation is a legal entity separate from its owners, giving shareholders limited liability in exchange for subjecting the firm to double taxation and regulatory oversight.",
    "anchorSummary": "Corporations are separate legal entities — owners risk only their investment, but profits are taxed twice.",
    "mechanism": "The corporation is the most powerful and legally complex business form. Its defining feature is that it is a legal person — it can enter contracts, own property, sue and be sued, and take on debt in its own name. This separateness means shareholders have limited liability: they can lose their investment if the company fails, but creditors cannot come after their personal assets. This protection is what makes it possible for millions of people to invest small amounts in companies they'll never visit, run, or fully understand — the foundation of modern capital markets.\n\nCorporations issue shares of stock, which represent fractional ownership. Shares can be transferred freely (sold to other investors), which creates liquidity and allows corporations to raise capital from a large pool of investors through stock exchanges. A board of directors represents shareholders, hires and oversees the CEO, and sets major strategic direction. Day-to-day management is delegated to professional executives.\n\nThe cost of this structure is double taxation: the corporation pays corporate income tax on its profits, and shareholders pay personal income tax on dividends distributed from those already-taxed profits. The S-corporation (available to smaller companies with fewer than 100 shareholders) avoids double taxation via pass-through treatment but imposes restrictions on ownership. The C-corporation has no such restrictions and is required for publicly traded companies. How this connects to other business functions: corporations can raise capital through stock and bond issuance, enabling the scale of investment that no sole proprietor or partnership could achieve — this capital capacity is what makes massive operations, marketing, and R&D possible.",
    "mechanismSummary": "The corporation's limited liability and share transferability unlock large-scale capital raising at the cost of regulatory complexity and double taxation.",
    "boundaryConditions": "Limited liability is not absolute. Courts can 'pierce the corporate veil' and hold shareholders personally liable if they find the corporation was used fraudulently, was not properly maintained as a separate entity (co-mingling personal and corporate funds), or was undercapitalized. Additionally, the agency problem — executives (agents) may act in their own interests rather than shareholders' (principals) — is a structural weakness of the corporation; shareholders are often too dispersed to effectively monitor management.",
    "example": "When Tesla went public in 2010, it raised $226 million by selling shares to public investors. None of those investors would have put money in if they could personally be sued when a Tesla caught fire or if they would owe Tesla's debts if the company failed. The corporate structure made that investment possible. A decade later, Tesla's market capitalization exceeded $1 trillion, financed by equity from millions of shareholders and debt from institutional lenders — capital that no sole proprietorship or partnership could have assembled. Elon Musk's personal stake gave him influence over strategy, but he could not unilaterally bind other shareholders to personal liability.",
    "bridgeToAbstract": "The corporation's legal structure — limited liability, perpetual existence, share transferability — is the engine that makes large-scale business possible. Every modern public company you know exists because investors were willing to provide capital under those terms. Understanding the corporate form is understanding how most of the world's large businesses are organized.",
    "keyPoints": [
      "Limited liability means shareholders lose their investment if the company fails — they do not owe the company's debts; this distinction is foundational to understanding stock markets",
      "Double taxation (C-corp) vs. pass-through (S-corp, LLC) is a real financial decision with meaningful dollar consequences, not just a technicality",
      "The separation of ownership (shareholders) and control (executives) creates the agency problem — the foundational tension in corporate governance that affects every functional area"
    ]
  },
  "limited-liability-companies-mie201": {
    "openingQuestion": "Amazon, Google, and Nike are corporations. Your neighborhood restaurant is probably an LLC. Why did the most successful hybrid business structure in legal history become the default choice for small and medium businesses in America — and why didn't it exist until 1977?",
    "anchor": "An LLC combines the limited liability of a corporation with the pass-through taxation and management flexibility of a partnership.",
    "anchorSummary": "LLCs give owners liability protection and pass-through taxes without corporate formality requirements.",
    "mechanism": "The limited liability company (LLC) is a relatively recent invention — Wyoming enacted the first LLC statute in 1977, and all 50 states had LLC statutes by 1996. The LLC was designed to solve the major drawbacks of both corporations and partnerships simultaneously.\n\nLike a corporation, an LLC shields its members (the LLC equivalent of shareholders) from personal liability for the firm's debts and legal judgments — their risk is limited to their investment in the LLC. Unlike a C-corporation, an LLC's income flows through to members' personal tax returns, avoiding double taxation. Unlike a general partnership, members can limit their involvement in management without losing liability protection.\n\nLLCs are governed by an operating agreement, which can be almost infinitely customized: it specifies how profits and losses are allocated, who has management authority, what happens when a member wants to exit, and how decisions are made. This flexibility makes LLCs ideal for businesses with a small number of investors who want to customize their arrangement. The tradeoff is that LLCs cannot issue publicly traded stock, limiting their ability to raise capital at scale from thousands of investors. How this connects to other business functions: the LLC's flexibility means each functional decision — how much each member gets paid, how marketing authority is divided, who approves capital expenditures — is negotiated once in the operating agreement rather than governed by corporate law defaults.",
    "mechanismSummary": "The LLC is the best-of-both-worlds hybrid: limited liability without double taxation, and flexible management without corporate formality.",
    "boundaryConditions": "LLCs are not ideal for all situations. If a business plans to seek venture capital funding, most VC firms prefer C-corporations because their legal structure is better suited to issuing multiple classes of stock, granting stock options, and eventually going public. The flexibility that makes LLCs attractive for small businesses makes them less compatible with the standardized investor protections that institutional capital requires. Also, LLCs in some states must dissolve when a member leaves (absent operating agreement provisions), unlike corporations which have perpetual existence.",
    "example": "When two friends start a food product company — say, a specialty hot sauce — they almost certainly form an LLC. The LLC protects each friend's personal assets if a customer is injured and sues. The income flows through to their personal returns at their individual tax rates (likely lower than the corporate rate). The operating agreement specifies that one partner manages production and the other manages marketing, and both must approve any decision over $10,000. If the hot sauce takes off and they want venture capital to go national, they'll convert to a C-corporation — the VC will require it.",
    "bridgeToAbstract": "The LLC has become the default business form for entrepreneurs who want legal protection without corporate complexity. Understanding its trade-offs — no public equity, VC incompatibility — helps explain why the corporate form still dominates large-scale enterprise even though the LLC is objectively more flexible for small-scale ventures.",
    "keyPoints": [
      "LLCs are often confused with corporations — the key difference is pass-through taxation and the absence of shareholders; LLC owners are called members",
      "Venture capital firms almost always require conversion to a C-corporation as a condition of investment — the LLC's tax flexibility conflicts with the equity structure institutional investors need",
      "The operating agreement is the LLC's governing document — it determines how every function (management, finance, profit distribution) works, and neglecting to draft it carefully creates disputes later"
    ]
  },
  "franchises-cooperatives-nonprofits": {
    "openingQuestion": "There are over 13,000 McDonald's in the United States, but McDonald's corporate only owns about 5% of them. The other 95% are run by franchisees who paid McDonald's hundreds of thousands of dollars for the right to use the golden arches. Who is actually 'in charge' of a McDonald's — the owner behind the counter or McDonald's corporate?",
    "anchor": "Franchises, cooperatives, and nonprofits are specialized business forms built on shared systems, shared ownership, or shared mission rather than individual profit maximization.",
    "anchorSummary": "Specialized forms — franchises, co-ops, and nonprofits — organize around shared systems, shared ownership, or mission, not just individual profit.",
    "mechanism": "A franchise is a licensing arrangement in which the franchisor (the brand owner, like McDonald's or Subway) grants the franchisee (an independent operator) the right to use its brand, systems, and supply chain in exchange for an upfront fee and ongoing royalties. The franchisee owns and operates the location but must follow the franchisor's operational standards, marketing guidelines, and purchasing requirements. This gives the franchisee an established brand and proven system with lower startup risk; it gives the franchisor rapid expansion without using its own capital. The tension: the franchisee bears the local risk but has limited operational autonomy.\n\nA cooperative (co-op) is owned by the people it serves — its customers, workers, or suppliers. REI (outdoor gear) is a consumer co-op: members pay dues and receive profit-sharing dividends. Ocean Spray is an agricultural co-op owned by its cranberry-farming members. Mondragon in Spain is a worker co-op employing 80,000+ people. Co-ops distribute surplus to members rather than outside shareholders, aligning incentives between the business and the people it serves.\n\nA nonprofit organization pursues a mission rather than profit. Surplus revenue must be reinvested in the mission, not distributed to owners. Nonprofits can earn revenue, pay employees, and operate large complex organizations — hospitals, universities, and the NFL are all (or were) nonprofits. The restriction is on private inurement: no individual can personally pocket the surplus. How this connects to other business functions: each form reshapes the incentive structure underlying every function — franchises must align franchisor and franchisee incentives across marketing and operations; co-ops must manage democratic governance across financial and strategic decisions; nonprofits must balance mission and financial sustainability.",
    "mechanismSummary": "Franchises scale via licensed systems, co-ops align owners and customers, and nonprofits reinvest surplus into mission — each form reshapes incentives.",
    "boundaryConditions": "These forms are not always as clean as they appear. Franchises can create serious conflicts when the franchisor's brand priorities (pricing, marketing, menu changes) conflict with the franchisee's local profitability. Co-ops can become inefficient when democratic governance slows strategic decision-making. Nonprofits can develop mission drift when the need to generate revenue creates commercial activities that crowd out the original purpose.",
    "example": "Chick-fil-A is one of the most unusual franchises in America: its franchisees pay a relatively low $10,000 upfront (McDonald's charges $45,000+) but must work full-time in the restaurant themselves, and Chick-fil-A corporate retains ownership of the building and equipment. Chick-fil-A selects fewer than 1% of applicants and exercises unusually tight control over operations. The result: Chick-fil-A locations average more sales per restaurant than any other fast food chain. The franchise model was deliberately designed to maximize operational standards by ensuring each franchisee had skin in the game and no absentee ownership.",
    "bridgeToAbstract": "Understanding alternative business forms reveals that organizing a business is a design problem — the choice of form shapes who has decision authority, who bears risk, who captures profit, and how each function operates. There is no universally best form; the right choice depends on the mission, the capital needs, and the stakeholder relationships the business wants to create.",
    "keyPoints": [
      "Franchisees are independent business owners, not employees — they bear real financial risk and have real decision authority within the franchisor's system",
      "Co-ops have democratic governance, which creates accountability but can slow decision-making compared to investor-owned firms where executives have concentrated authority",
      "Nonprofits can be enormous, commercially sophisticated organizations — the nonprofit tax status restricts profit distribution, not operational scale or revenue generation"
    ]
  },
  "choosing-a-business-form": {
    "openingQuestion": "If you were starting a business today with a college friend, someone just pulled you aside and said: 'Don't shake hands and start working — you'll regret it.' What legal and financial decisions do you actually need to make before you start, and why do they matter?",
    "anchor": "Choosing a business form requires trading off liability protection, tax treatment, capital access, management flexibility, and administrative cost — there is no dominant choice across all dimensions.",
    "anchorSummary": "Business form choice trades liability, taxes, capital access, and management control — pick the combination that fits your risk and growth plan.",
    "mechanism": "The decision framework for choosing a business form centers on five questions:\n\n1. Liability: How much personal risk can the owners tolerate? If the business could generate lawsuits or large debts, limited liability (LLC, corporation) is essential. If risk is minimal (freelance writing, tutoring), a sole proprietorship may suffice.\n\n2. Taxes: Do the owners prefer pass-through taxation (sole prop, partnership, S-corp, LLC) or are they willing to accept double taxation in exchange for other corporate benefits? Most small businesses prefer pass-through.\n\n3. Capital: How much external money will the business need, and from whom? Venture capital requires a C-corp. Bank loans work with any form. Small businesses funding from savings can use any structure.\n\n4. Management control: Do owners want to retain full control, or are they comfortable with a board of directors, fiduciary duties to shareholders, and disclosure requirements?\n\n5. Administrative burden: Corporations require annual filings, board meetings, minutes, and compliance obligations. Sole proprietorships require almost nothing. LLCs fall in between.\n\nThe choice evolves over time: many successful businesses start as sole proprietorships, become LLCs as they grow, and convert to C-corporations if they pursue venture capital or an IPO. How this connects to other business functions: the business form determines who controls major financial decisions, who receives profits, how accounting is structured, and how much compliance the operations team must manage.",
    "mechanismSummary": "Liability, taxes, capital access, control, and admin burden are the five dimensions to trade off; the right form often changes as the business grows.",
    "boundaryConditions": "The choice can be complicated by state-specific laws (some states are more LLC-friendly than others), international operations (the U.S. form doesn't automatically transfer abroad), and industry-specific regulations (professional service firms like law and medicine often have restrictions on their business form). Tax law changes can also shift the calculus — the 2017 Tax Cuts and Jobs Act lowered the corporate rate, making C-corporation status more attractive relative to pass-through entities than it had been previously.",
    "example": "Instagram started as a sole venture by Kevin Systrom, quickly became an LLC, then converted to a Delaware C-corporation before raising venture capital. Each transition was driven by a new constraint: first the need for liability protection, then the need to accommodate venture capital's equity requirements. When Facebook acquired Instagram for $1 billion in 2012, Instagram was a Delaware C-corporation — the only form that could accommodate that kind of institutional transaction cleanly. Had it remained an LLC, the acquisition would have required substantial legal restructuring.",
    "bridgeToAbstract": "Choosing a business form is one of the first and most consequential decisions any business makes — it sets the rules for ownership, liability, taxation, and governance that will govern every major function. Revisiting the choice as the business grows is not a sign of failure; it is normal and expected as capital needs and risk profiles change.",
    "keyPoints": [
      "There is no universally best business form — the right answer depends on the specific combination of liability risk, tax situation, capital needs, and growth plans",
      "Business form affects every function: accounting (reporting requirements), finance (capital sources), operations (owner involvement), marketing (brand and entity alignment)",
      "Conversion from one form to another (sole prop → LLC → C-corp) is common and expected as businesses scale — plan for the evolution rather than trying to pick the forever-final answer at the start"
    ]
  },
  "entrepreneurship": {
    "openingQuestion": "Sara Blakely invented Spanx by cutting the feet off her pantyhose and cold-calling hosiery mills until one agreed to manufacture her idea. She had no fashion industry experience, no investors, and no co-founder — just $5,000 in savings and a problem she personally experienced. How do we explain why she succeeded when most people with the same savings and the same idea wouldn't have?",
    "anchor": "Entrepreneurship is the process of identifying an opportunity, marshaling resources to pursue it, and bearing the risk that the outcome may fail.",
    "anchorSummary": "Entrepreneurship is opportunity identification plus resource assembly plus risk-bearing — all three are required.",
    "mechanism": "Entrepreneurship is often romanticized as a personality trait, but it is more accurately a process with identifiable steps. The process begins with opportunity recognition: seeing a gap between what currently exists and what customers actually need or want. This requires not just creativity but also a tolerance for searching — most good opportunities are not obvious and require deep familiarity with a specific domain, customer group, or technology.\n\nOnce an opportunity is identified, the entrepreneur must assemble resources: capital (savings, loans, investors), people (co-founders, early employees), and knowledge (technical, market, operational). This resource assembly is the primary challenge for most new ventures — the entrepreneur typically has the idea but not all the resources, which requires selling the vision to others before there is much evidence it will work.\n\nFinally, the entrepreneur must bear risk. Unlike an employee who receives a salary regardless of business performance, the entrepreneur's return is uncertain. They may work for years and earn nothing. This risk-bearing is why entrepreneurs are rewarded so richly when they succeed — it is compensation for years of uncertainty others chose not to accept.\n\nEntrepreneurship occurs inside large firms (called intrapreneurship) as well as in startups. Corporate entrepreneurs identify new opportunities within existing organizations, often with more resources but less autonomy. How this connects to other business functions: every business function must eventually be staffed by the entrepreneur or someone they hire — marketing, operations, finance, HR all start as entrepreneur responsibilities before being delegated to specialists.",
    "mechanismSummary": "Entrepreneurship is a process — opportunity recognition, resource assembly, risk-bearing — not a personality type; it occurs inside firms (intrapreneurship) and in startups.",
    "boundaryConditions": "Entrepreneurship is not synonymous with startups, innovation, or technology. A person buying a franchise, opening a dry cleaner, or taking over a family business is an entrepreneur in the economic sense even without creating a new product. The boundaries blur when 'entrepreneur' becomes a status symbol rather than a description of economic function — not everyone who calls themselves an entrepreneur is bearing meaningful risk or identifying genuine market opportunities.",
    "example": "Brian Chesky and Joe Gebbia could not pay their San Francisco rent in 2007. They bought air mattresses and rented space in their apartment to strangers attending a design conference. The 'opportunity' was not an obvious market gap — hotels existed everywhere. But they noticed that during peak events, no spare capacity existed at any price. That observation became Airbnb, valued at $75 billion at its IPO. The opportunity recognition was specific: a recurring, predictable demand spike that existing supply couldn't serve. The resource assembly was creative: using other people's homes as the supply. The risk was real: they spent months living off credit card debt before the idea worked.",
    "bridgeToAbstract": "Entrepreneurship is the factor of production that combines the others — land, labor, capital — into something new and valuable. Every business, regardless of size or age, can practice the entrepreneurial process: seeing opportunities others miss and mobilizing resources to pursue them before certainty arrives.",
    "keyPoints": [
      "Entrepreneurship is a process, not a personality trait — the 'lone genius' narrative ignores the role of team-building, resource assembly, and market timing",
      "Most startups fail not because the idea was bad but because of execution failures in resource assembly, timing, or market understanding",
      "Intrapreneurship (entrepreneurship inside large firms) is how most innovation at scale actually happens — big companies need entrepreneurial thinking but can offer resources startups can't access"
    ]
  },
  "problems-customers-opportunities": {
    "openingQuestion": "Kodak invented the digital camera in 1975 — 20 years before digital cameras became commercially viable. Kodak's engineers saw the technology. What they didn't see was the customer. What's the difference between having a technology and having an opportunity?",
    "anchor": "A business opportunity exists only when a real customer with a real problem is willing to pay more for a solution than it costs to deliver.",
    "anchorSummary": "Opportunities require a real customer, a real problem, and willingness to pay — technology or ideas alone are not enough.",
    "mechanism": "Many would-be entrepreneurs start with a solution: an interesting technology, a clever product idea, or a feature they wish existed. The customer-first approach inverts this: start with a specific customer segment experiencing a specific, painful problem, then ask whether a solution can be built economically.\n\nThe customer discovery process (popularized by Steve Blank) asks entrepreneurs to get out of the building and interview real customers before building anything. The goal is to verify three things: that the problem is real and frequent (not theoretical or rare), that customers are currently using workarounds that are costly or frustrating (indicating they would switch to a better solution), and that they would actually pay for the solution (not just say it sounds nice).\n\nOpportunities have three dimensions: magnitude (how many people have this problem, how painful is it), accessibility (can you reach those people, can you serve them profitably), and timing (is the market ready for this solution now — not too early, not too late). Kodak had the technology but lacked the timing: digital cameras in 1975 required hardware that cost thousands of dollars and produced inferior images. The opportunity arrived only when chip costs fell, storage became cheap, and the internet created a distribution and sharing infrastructure. How this connects to other business functions: identifying the customer's problem is a marketing function; designing the solution is a product/operations function; determining willingness to pay is a finance and pricing function — all must align around the same customer insight.",
    "mechanismSummary": "Opportunities require real customers, painful problems, willingness to pay, and the right timing — solution-first thinking misses most of this.",
    "boundaryConditions": "Customer discovery has limits. Customers often cannot articulate what they want before it exists — Henry Ford's famous (possibly apocryphal) quote about customers wanting 'a faster horse' points to the challenge of breakthrough innovation. Jobs and Wozniak didn't survey potential Apple II customers; they built something they themselves wanted. Customer feedback is most useful for refining existing categories of solutions and least useful for discovering entirely new ones.",
    "example": "Before Airbnb built anything, Chesky and Gebbia manually tested their hypothesis by photographing apartments in New York themselves, listing them on the site, and managing bookings by hand. They had real customers (travelers) with a real problem (no hotel availability during events) who demonstrated willingness to pay (they did pay). The manual approach confirmed the opportunity before automation was built. This is the 'Wizard of Oz' method: fake the product delivery manually to verify customer behavior before investing in infrastructure. Most startups that fail do so because they skipped this step.",
    "bridgeToAbstract": "Every business function serves a customer — but functions without a clear picture of who that customer is and what problem they face operate without alignment. The entrepreneur's first job is to define the customer clearly enough that everyone in the business understands who they are serving and why.",
    "keyPoints": [
      "A technology or feature is not an opportunity — an opportunity requires a customer who will pay; Kodak had the technology for 20 years before the customer context made it viable",
      "Willingness to pay is different from willingness to say 'that sounds great' — real opportunities are validated with actual purchase behavior, not survey responses",
      "Customer discovery connects to every function: marketing identifies the segment, operations must serve their needs, finance must model their willingness to pay — all functions need the same customer insight"
    ]
  },
  "business-models": {
    "openingQuestion": "Gillette sells razors at near cost and makes its money on blades. Adobe used to sell Photoshop for $700 and now charges $55 per month forever. Both are wildly profitable software and hardware companies. How can two such different pricing structures both work?",
    "anchor": "A business model is the logic by which a business creates, delivers, and captures value — it answers who the customer is, what problem is solved, how the solution is delivered, and how money is made.",
    "anchorSummary": "A business model answers: who is the customer, what value is delivered, how is it delivered, and how does money get made.",
    "mechanism": "Alexander Osterwalder's Business Model Canvas is the most widely used framework for mapping business models across nine building blocks: customer segments, value propositions, channels, customer relationships, revenue streams, key resources, key activities, key partnerships, and cost structure. These nine elements describe the full logic of how a business creates and captures value.\n\nThe core trade-off in any business model is between value delivery and value capture. A business can deliver enormous value to customers but capture very little of it if prices are low, costs are high, or competitors free-ride on its investments. A business can capture high margins but deliver little real value — which is rarely sustainable long-term.\n\nPlatform business models create value by connecting two or more groups (buyers and sellers, advertisers and readers, app developers and phone users) rather than by producing goods directly. Network effects — where the platform becomes more valuable as more people join — can create powerful competitive moats. The challenge is the cold-start problem: a platform with no users is worthless to any user, requiring a strategy to build both sides simultaneously.\n\nHow this connects to other business functions: the business model determines what operations must be built (to deliver the value proposition), what marketing must communicate (to attract the right segments), what finance must model (the unit economics of revenue vs. costs), and what HR must staff (the key activities).",
    "mechanismSummary": "A business model maps value creation, delivery, and capture — platform models create value by connecting groups and rely on network effects.",
    "boundaryConditions": "Business models can become obsolete when technology or regulation shifts the value chain. Newspapers had a profitable business model for a century: advertisers paid to reach subscribers. Google disaggregated that model by targeting ads more precisely and at lower cost, eliminating the economic rationale for bundling classifieds with news. A business model that works in one environment may be destroyed by a shift in technology, customer behavior, or regulation.",
    "example": "Spotify's business model is unusual: it pays record labels roughly 70% of its revenue as royalties, meaning it captures only 30 cents of every dollar it earns before operating costs. The bet is that massive scale — hundreds of millions of users — will generate enough 30-cent slices to be profitable, and that switching costs (playlists, algorithmic personalization, social features) will keep users from leaving. As of 2024, Spotify had 600 million users and had only recently begun generating consistent operating profits. The business model works only at enormous scale — at smaller scale, the royalty structure makes it impossible to profit.",
    "bridgeToAbstract": "The business model is the skeleton of the business — everything else (operations, marketing, finance, HR) is built on top of it. Changing the business model can create more value than improving any individual function, but it also disrupts every function simultaneously, which is why incumbents resist model change even when they can see it coming.",
    "keyPoints": [
      "Students often confuse business model with product — the product is one component; the business model specifies the entire logic of how the product creates and captures value",
      "Platform business models (two-sided markets) behave differently from product businesses — their economics depend on network effects and managing both sides of the market simultaneously",
      "Business model and strategy interact: a superior product with a weak business model fails; a mediocre product with a strong model (locking in customers, high switching costs) can dominate"
    ]
  },
  "revenue-models": {
    "openingQuestion": "Google is one of the most valuable companies in history. You use it dozens of times a day. You have never paid Google a single dollar. Who is actually Google's customer — and what are they buying?",
    "anchor": "A revenue model specifies who pays, how much, when, and in exchange for what — it is distinct from, but embedded within, the broader business model.",
    "anchorSummary": "Revenue models define who pays, how much, and when — the mechanics of how a business converts value into money.",
    "mechanism": "Revenue model choice shapes everything about how a business operates. The main types:\n\nTransaction-based: one payment for one purchase. The simplest model — Amazon selling a book, a car dealership selling a car. Revenue is lumpy (comes in one-time chunks) and requires constant acquisition of new customers or repeat purchases.\n\nSubscription: recurring payment for ongoing access. SaaS companies (Netflix, Spotify, Salesforce), gyms, and newspapers use this model. Revenues are more predictable; customer acquisition cost is amortized over the lifetime of the subscription; churn (subscription cancellations) is the critical metric.\n\nFreemium: a free tier attracts users; a paid tier (with more features, capacity, or no ads) generates revenue. Spotify, Dropbox, LinkedIn all use freemium. The challenge is converting enough free users to paid to cover the cost of serving all users, including the free tier.\n\nAdvertising: charge businesses for access to an audience. Google, Meta, and most news websites use this model. The user is the product, not the customer. Revenue depends on audience size, engagement, and targeting capability.\n\nCommission/marketplace: take a percentage of transactions between third parties. Airbnb, Uber, and eBay use this model. The platform doesn't own inventory; it earns a cut of every transaction it enables.\n\nLicensing: charge for the right to use intellectual property — patents, brands, software. Qualcomm makes most of its money licensing chip patents it never manufactures itself.\n\nHow this connects to other business functions: revenue model determines cash flow patterns (transaction = lumpy; subscription = smooth), which shapes financial planning; it determines customer relationship design, which shapes marketing; it determines what operations delivers (a one-time product vs. ongoing service).",
    "mechanismSummary": "Revenue model type (transaction, subscription, freemium, advertising, commission, licensing) shapes cash flow, customer relationships, and every function downstream.",
    "boundaryConditions": "Many businesses combine multiple revenue models — Apple sells hardware (transaction), charges developers a commission through the App Store (marketplace), offers iCloud (subscription), and licenses its software to enterprise customers. Multi-model businesses can capture more of the value they create but become more complex to manage. Revenue model transitions (moving from transaction to subscription, as Adobe did) can create short-term revenue drops even when the long-term economics improve.",
    "example": "Adobe's 2013 transition from selling Creative Suite as a $700 one-time purchase (transaction) to Creative Cloud as a $55/month subscription (subscription) was met with user outrage but proved financially transformative. In the transaction model, Adobe earned revenue only when it released a new version (every 18–24 months) and only from customers who chose to upgrade. In the subscription model, it earned monthly revenue from every active user continuously. By 2023, Adobe's annual recurring revenue exceeded $17 billion — more than five times its pre-subscription revenue. The business model change required no change in the product; it changed only who pays, when, and how much.",
    "bridgeToAbstract": "Revenue model is not a technical detail — it determines how a business's economics work, how customers relate to the product, and how every function must be designed. Changing the revenue model is often the highest-leverage strategic move available, but it requires transforming operations, marketing, finance, and customer relationships simultaneously.",
    "keyPoints": [
      "In an ad-supported model (Google, Facebook), the user is not the customer — advertisers are; this shapes every product and marketing decision",
      "Subscription economics depend on churn rate and customer lifetime value — a business with high churn needs to acquire customers faster than it loses them, often at unsustainable cost",
      "Revenue model transitions disrupt every function: Adobe's shift to subscription changed how finance modeled cash flow, how marketing acquired customers, and how operations supported ongoing access rather than one-time delivery"
    ]
  },
  "innovation": {
    "openingQuestion": "The iPhone launched in 2007 with almost no apps, no 3G, no cut-and-paste, and a price that was double most competing smartphones. By 2012 it had 700,000 apps and controlled most of the smartphone market's profits. Nokia had better specs, better distribution, and more customers. Why did it lose?",
    "anchor": "Innovation is the process of creating and implementing ideas that generate new value — it is distinct from invention, which creates new ideas but doesn't necessarily deliver them to market.",
    "anchorSummary": "Innovation creates and delivers new value; invention creates new ideas — innovation requires both the idea and successful implementation.",
    "mechanism": "Innovation types form a spectrum from incremental to disruptive. Incremental innovation improves existing products or processes along established dimensions — faster chips, lower-cost manufacturing, improved battery life. Disruptive innovation (Clayton Christensen's framework) introduces a product that is initially inferior on established metrics but superior on a new dimension customers hadn't prioritized — simplicity, convenience, price — and eventually displaces incumbents as the new dimension becomes dominant.\n\nChristensen's core insight: incumbents fail not because they are poorly managed but because they are well managed. They optimize for their best customers (who want better, more expensive products) and ignore the low end of the market (customers who want 'good enough' at low cost). Disruptors enter at the low end, improve over time, and eventually displace the incumbent. This is exactly what happened to Nokia: Nokia optimized for its large business customers who wanted sophisticated phone features. Apple entered for consumers who wanted simplicity. By the time Apple's product was sophisticated enough for business users, Nokia had already lost the consumer market that would fund its next generation of investment.\n\nOpen vs. closed innovation: firms can innovate internally (R&D labs) or by collaborating with external partners, universities, startups, or customers. Open innovation (Chesbrough) recognizes that not all valuable ideas originate inside the firm — which is why companies like Procter & Gamble use open innovation programs to source ideas globally. How this connects to other business functions: innovation in product requires collaboration between R&D (new ideas), operations (can it be built?), marketing (will customers want it?), and finance (does the economics work?). All four functions must align for innovation to actually reach the market.",
    "mechanismSummary": "Disruptive innovation enters at the low end on a new dimension, then improves — incumbents optimizing for existing customers miss it until too late.",
    "boundaryConditions": "The disruptive innovation framework is powerful but not universal. Sometimes incumbents do successfully respond to disruption (Netflix vs. Blockbuster, where Blockbuster actually launched a competing streaming service before being undercut on price). Sometimes disruption fails to materialize — autonomous vehicles have been 'disrupting' transportation for a decade without displacing traditional cars. The framework explains past disruptions more reliably than it predicts future ones.",
    "example": "Airbnb disrupted hotels by being initially inferior on nearly every hotel metric: no 24-hour front desk, no room service, no guaranteed cleanliness standards, no loyalty points. But it was dramatically better on two dimensions incumbents couldn't match: price (for long stays) and authenticity (living in a neighborhood rather than a hotel district). Hotels dismissed Airbnb as serving backpackers and budget travelers — exactly the low-end customers they didn't prioritize. By the time Airbnb was competing for business travelers and premium customers, it had achieved global scale that no hotel chain could replicate without owning physical assets.",
    "bridgeToAbstract": "Every business must innovate to survive because markets, technologies, and customer expectations all change. The question is not whether to innovate but what type of innovation to pursue — incremental improvements to the current offering or new approaches that address unmet needs. Getting this wrong (too much incremental, missing disruption) is how market leaders lose their positions.",
    "keyPoints": [
      "Disruptive innovation is not the same as better innovation — it is often initially worse on existing metrics but superior on a new dimension that incumbents undervalue",
      "Incumbents often see disruption coming and still fail to respond because their existing customers, revenue streams, and internal incentives pull them toward the existing business model",
      "Innovation requires alignment across all functions: R&D generates ideas, but operations must build it, marketing must sell it, and finance must fund it — misalignment in any function kills innovations that are technically brilliant"
    ]
  },
  "startup-challenges": {
    "openingQuestion": "About 90% of startups fail within 10 years. But most founders who start companies are smart, motivated, hardworking people with real ideas. If talent and effort aren't the bottleneck, what actually kills startups?",
    "anchor": "Startups fail most often not because the idea was bad but because of predictable execution failures: running out of cash, misjudging the market, or building the wrong team.",
    "anchorSummary": "Startups usually fail from cash depletion, market misread, or team problems — not from bad ideas.",
    "mechanism": "CB Insights analyzed 300 startup postmortems and found the top three causes of failure: no market need (42%), ran out of cash (29%), and not the right team (23%). These categories reveal the core challenge: startups must simultaneously identify a real market need, execute at speed before running out of money, and build a team capable of doing both.\n\nThe Valley of Death is the period between a startup's initial funding and its first significant revenue — typically 12–24 months. During this period, the startup burns cash (rent, salaries, infrastructure) while building the product and acquiring initial customers. If customers arrive more slowly or pay less than expected, the startup may exhaust its cash before generating enough revenue to survive. This creates a constant tension: spend to acquire customers quickly (which consumes cash) vs. conserve cash (which delays the revenue needed to survive).\n\nSmall businesses face a different version of these challenges. They typically have less access to venture capital, depend on a single revenue source or location, and are run by an owner who must be expert in all functions simultaneously. The Small Business Administration estimates that about 20% of small businesses fail in year one, 45% by year five, and 65% by year ten. Cash flow management — not accounting profit — is the primary financial challenge: a small business can be technically profitable but fail because customers pay slowly and suppliers must be paid quickly.\n\nHow this connects to other business functions: the top startup failures are failures of specific functions — market need is a marketing failure, cash is a finance failure, team is an HR and leadership failure. Understanding these functions is not academic; they directly correspond to the most common failure modes.",
    "mechanismSummary": "Startups die from no market need, cash depletion, and team problems — each maps directly to a core business function that must be managed simultaneously.",
    "boundaryConditions": "Survival rates improve dramatically with prior entrepreneurial experience, access to strong mentors and networks, industry-specific knowledge, and sufficient initial capitalization. The 90% failure rate averages across all types of startups — a first-time founder in an unfamiliar industry with minimal capital faces far worse odds than a repeat founder in a domain they know well who has raised adequate funding.",
    "example": "Juicero was a Silicon Valley startup that raised $120 million to build a $400 wifi-connected juicing machine. In 2017, Bloomberg published a video showing that the Juicero's proprietary juice packets could be squeezed by hand to produce the same juice in the same time as the machine — revealing that the $400 device added no value. The startup had no market need (its own product was redundant), and its cash had been spent building sophisticated hardware and distribution for a problem customers didn't have. It shut down within a month of the story publishing. The failure wasn't execution — it was a fundamental market need failure that $120 million couldn't fix.",
    "bridgeToAbstract": "Startup and small-business challenges are concentrated versions of the challenges all businesses face: finding customers who value what you do, managing cash to survive long enough to scale, and building a team that executes. The intensity and speed of these challenges in early-stage businesses is why studying entrepreneurship requires simultaneous fluency across all business functions.",
    "keyPoints": [
      "The most common startup failure (42%) is no market need — founders often build what they think customers want rather than what customers actually need and will pay for",
      "Cash flow is not the same as profit — a business can be profitable on paper and still fail because it runs out of cash if customers pay slowly and suppliers must be paid quickly",
      "Every common failure mode maps to a function: no market need = marketing failure, cash = finance failure, wrong team = HR/leadership failure — understanding functions is understanding survival requirements"
    ]
  }
}

def main():
    data = json.loads(COURSE_PATH.read_text())

    slug_to_learn = LEARN

    updated = 0
    for unit in data["units"][:9]:  # Units 1-9 only
        for topic in unit["topics"]:
            if topic["slug"] in slug_to_learn:
                topic["learn"] = slug_to_learn[topic["slug"]]
                updated += 1

    COURSE_PATH.write_text(json.dumps(data, indent=2, ensure_ascii=False))
    print(f"Updated {updated} topics with learn content.")

if __name__ == "__main__":
    main()
